export const ERROR_CODES = {
  AUTH_FAILED: 'AUTH_FAILED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROXY_UNAVAILABLE: 'PROXY_UNAVAILABLE',
  STREAM_ERROR: 'STREAM_ERROR',
  TIMEOUT: 'TIMEOUT',
  RATE_LIMITED: 'RATE_LIMITED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

const RETRYABLE_CODES = new Set<ErrorCode>([
  ERROR_CODES.PROXY_UNAVAILABLE,
  ERROR_CODES.TIMEOUT,
  ERROR_CODES.STREAM_ERROR,
  ERROR_CODES.RATE_LIMITED,
  ERROR_CODES.NETWORK_ERROR,
]);

export function isRetryableError(code: string): boolean {
  return RETRYABLE_CODES.has(code as ErrorCode);
}
